# Generated by Django 3.2.15 on 2023-02-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=256)),
                ('port', models.IntegerField(default=8443)),
            ],
        ),
        migrations.DeleteModel(
            name='MQTT',
        ),
    ]
