# Generated by Django 3.2.15 on 2023-02-26 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_auto_20230222_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intergration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PF', 'Platform'), ('HB', 'Heartbeat')], max_length=2)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('hint', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
