# Generated by Django 3.2.15 on 2023-04-05 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_logs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logs',
            new_name='Log',
        ),
    ]
