# Generated by Django 3.2.15 on 2023-04-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_rename_logs_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='code',
            field=models.IntegerField(),
        ),
    ]
