# Generated by Django 3.2.15 on 2023-02-26 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_auto_20230226_1945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Heartbeat',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
