# Generated by Django 3.2.15 on 2023-04-05 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_alter_log_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='messages',
            new_name='message',
        ),
    ]
