# Generated by Django 3.2.15 on 2023-04-05 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_rename_messages_log_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='identity.integration'),
        ),
    ]
