# Generated by Django 3.2.15 on 2023-04-05 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_alter_log_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
