# Generated by Django 3.2.15 on 2023-02-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='balloon',
            field=models.IntegerField(choices=[(1, 'B1'), (2, 'B2'), (3, 'B3')], unique=True),
        ),
    ]
