# Generated by Django 3.2.15 on 2023-02-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_challenge_balloon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
