# Generated by Django 3.2.15 on 2023-03-15 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('game', '0002_alter_challenge_balloon'),
    ]

    operations = [
        migrations.AddField(
            model_name='solve',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='solves', to='team.team'),
            preserve_default=False,
        ),
    ]
