# Generated by Django 3.2.15 on 2023-03-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_solve_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solve',
            name='node',
        ),
    ]
