# Generated by Django 3.2.15 on 2023-03-28 16:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machineid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('heartbeats', models.BooleanField(blank=True, null=True)),
                ('initialized', models.DateTimeField(blank=True, null=True)),
                ('heartbeat', models.DateTimeField(blank=True, null=True)),
                ('internval', models.IntegerField(blank=True, null=True)),
                ('state', models.JSONField(blank=True, default=None, null=True)),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node', to='team.team')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17, unique=True)),
                ('address', models.CharField(blank=True, max_length=17, null=True)),
                ('subnet', models.CharField(blank=True, max_length=17, null=True)),
                ('gateway', models.CharField(blank=True, max_length=17, null=True)),
                ('dns', models.CharField(blank=True, max_length=17, null=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='networking', to='node.node')),
            ],
        ),
    ]
