# Generated by Django 3.2.15 on 2023-03-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='ssid',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
