# Generated by Django 3.2.15 on 2023-03-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='state',
            field=models.JSONField(default={'hi': 'hello'}, verbose_name='testing'),
        ),
    ]
