# Generated by Django 3.2.15 on 2023-03-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_node_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='state',
            field=models.JSONField(null=True),
        ),
    ]
