# Generated by Django 3.2.15 on 2023-02-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_auto_20230221_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='subnet',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
