# Generated by Django 3.2.15 on 2023-02-27 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('node', '0002_node_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node', to='team.team'),
        ),
    ]
