# Generated by Django 3.2.15 on 2023-03-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_alter_node_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='state',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
