# Generated by Django 3.2.15 on 2023-04-06 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_alter_network_ssid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(choices=[('P1', 'P1'), ('P3', 'P2'), ('P3', 'P3'), ('P4', 'P4')], max_length=2)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='node.node')),
                ('rom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='node.rom')),
            ],
        ),
    ]
